# Generated by Django 6.1 on 2026-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('developer', 'Developer'), ('corporate', 'Corporate'), ('creative', 'Creative'), ('glass', 'Glass'), ('dark', 'Dark'), ('pulse', 'Pulse'), ('aurora', 'Aurora'), ('bold', 'Bold')], default='minimal', max_length=20),
        ),
    ]
