# Generated by Django 6.1 on 2026-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('developer', 'Developer'), ('corporate', 'Corporate'), ('creative', 'Creative'), ('glass', 'Glass'), ('dark', 'Dark'), ('pulse', 'Pulse'), ('aurora', 'Aurora'), ('bold', 'Bold'), ('racer', 'Racer')], default='minimal', max_length=20),
        ),
    ]
