# Generated by Django 6.1 on 2026-08-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_color',
            field=models.CharField(default='#E8231A', max_length=7),
        ),
    ]
