# Generated by Django 6.1 on 2026-08-09 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('bio_generate', 'Génération de bio'), ('bio_improve', 'Amélioration de bio'), ('project_description', 'Description de projet'), ('skill_suggestions', 'Suggestions de compétences'), ('profile_analysis', 'Analyse du profil'), ('assistant', 'Assistant professionnel')], max_length=30)),
                ('prompt_input', models.TextField(blank=True)),
                ('response_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
