# Generated by Django 6.1 on 2026-08-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='request_type',
            field=models.CharField(choices=[('bio_generate', 'Génération de bio'), ('bio_improve', 'Amélioration de bio'), ('skill_suggestions', 'Suggestions de compétences'), ('profile_analysis', 'Analyse du profil'), ('assistant', 'Assistant professionnel')], max_length=30),
        ),
    ]
